version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: usertracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: TT4242@mtskr
      MYSQL_DATABASE: UserService_db
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - usertracker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: .
    container_name: usertracker-server
    depends_on:
      mysql:
        condition: service_healthy
    
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/UserService_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: TT4242@mtskr
    networks:
      - usertracker-network

networks:
  usertracker-network:
    driver: bridge

volumes:
  mysql-data: